apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server-crud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-crud
  template:
    metadata:
      labels:
        app: server-crud
    spec:
      containers:
      - name: server-crud
        image: likerpic/server_crud:1.0
        ports:
        - containerPort: 8000
        env:
          - name: SRV_DB_USR
            valueFrom:
              secretKeyRef:
                name: sc-server-env
                key: SRV_DB_USR
          - name: SRV_DB_PWD
            valueFrom:
              secretKeyRef:
                name: sc-server-env
                key: SRV_DB_PWD
          - name: SRV_DB_NAME
            valueFrom:
              secretKeyRef:
                name: sc-server-env
                key: SRV_DB_NAME
          - name: SRV_DB_HOST
            valueFrom:
              secretKeyRef:
                name: sc-server-env
                key: SRV_DB_HOST
          - name: SRV_DB_PORT
            valueFrom:
              secretKeyRef:
                name: sc-server-env
                key: SRV_DB_PORT

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-pg
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: pg-base
  template:
    metadata:
      labels:
        app: pg-base
    spec:
      containers:
        - name: pg-server
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: sc-pg-env
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sc-pg-env
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sc-pg-env
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: vol-pg-data
              mountPath: /var/lib/postgresql/data
            - name: vol-pg-init
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: vol-pg-init
          configMap:
            name: cm-pg-init

        - name: vol-pg-data
          persistentVolumeClaim:
            claimName: pvc-pg