apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pg
  labels:
    type: local
    app: my-database
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"