apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solution-auth-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /auth/health
        pathType: Prefix
        backend:
          service:
            name: svc-auth
            port:
              number: 8000
      - path: /auth/metrics
        pathType: Prefix
        backend:
          service:
            name: svc-auth
            port:
              number: 8000
      - path: /register
        pathType: Prefix
        backend:
          service:
            name: svc-auth
            port:
              number: 8000
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: svc-auth
            port:
              number: 8000
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: svc-user
            port:
              number: 8000              
