apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pg-auth
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pg-user
spec:
  storageClassName: manual2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi