{
 "title": "Server CRUD",
 "time": { "from": "2024-08-05T06:51:22.300Z", "to": "2024-08-05T07:21:22.300Z" },
 "panels": [
  {
   "title": "API RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(api) (rate(req_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API TPM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (api) (increase(req_total[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "sum by(api) (req_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Resp Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(code) (rate(resp_code[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Квантиль 0.5 с",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(dur_sec_bucket[1m])) by (le,api))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Квантиль 0.15 с",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.15, sum by(le,api) (rate(dur_sec_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}