apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-crud-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: svc-server-crud
            port:
              number: 8000
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: svc-server-crud
            port:
              number: 8000
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: svc-server-crud
            port:
              number: 8000
