apiVersion: v1
kind: Service
metadata:
  name: svc-pg-server
  labels:
    app: pg-base
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: pg-base

---

apiVersion: v1
kind: Service
metadata:
  name: svc-server-crud
  labels:
    app: server-crud
spec:
  selector:
    app: server-crud
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: metrics